"""
Predetermines fallback creative ideas for ideate tool.
"""

responses = [
    "An umbrella that appears when it rains",
    "A pen that never runs out of ink",
    "A shirt that cleans itself",
    "A mug that keeps your drink at the perfect temperature",
    "A backpack that charges your devices as you walk",
    "A pillow that adjusts to your sleeping position",
    "A water bottle that tracks your hydration",
    "A wallet that finds your phone",
    "A plant pot that waters itself",
    "A bike lock that texts you if tampered with",
    "A calendar that schedules breaks for you",
    "A lamp that mimics natural sunlight",
    "A mirror that gives you compliments",
    "A doormat that cleans your shoes automatically",
    "A notebook that digitizes your notes",
    "A suitcase that follows you around the airport",
    "A bookmark that remembers where you stopped reading",
    "A coffee table that charges your laptop wirelessly",
    "A fridge that suggests recipes based on contents",
    "A toothbrush that plays your favorite song",
    "A keychain that finds your keys",
    "A scarf that changes color with your mood",
    "A trash can that sorts recyclables automatically",
    "A remote that finds itself when lost",
    "A clock that wakes you up at the lightest sleep phase",
    "A pen that translates as you write",
    "A mug that stirs itself",
    "A wallet that counts your cash",
    "A phone case that cleans your screen",
    "A plant that glows when it needs water",
    "A chair that adjusts to your posture",
    "A window that tints automatically in sunlight",
    "A shoe that tracks your steps and posture",
    "A hat that cools you in summer",
    "A container that reminds you of the contents",
    "A charger that works with any device",
    "A notebook that never runs out of pages",
]
